version: '3'
services:
  web:
    image: howie6879/tushu
    command: pipenv run gunicorn -c tushu/config/gunicorn.py --worker-class sanic.worker.GunicornWorker tushu.server:app
    ports:
     - "8001:8001"
    volumes:
     - .:/tushu